### PR TITLE
fix: Improve ReceiveMessagesTest with log asserts

### LINKED ISSUE #49: Tests for incoming messages don't check that failure is due to the right reason
I think we should improve the tests for the following because it's far too easy to write tests that fail for the wrong reason:

https://github.com/relaycorp/relaynet-endpoint-android/blob/95a47a627f31fc4d5715b029ea7e342839b7e6d3/lib/src/main/java/tech/relaycorp/relaydroid/messaging/ReceiveMessages.kt#L68-L91

Maybe we should inspect the logs?

For example, the current implementation has a bug which the tests aren't uncovering: There are two catch blocks for the same exception:

https://github.com/relaycorp/relaynet-endpoint-android/blob/95a47a627f31fc4d5715b029ea7e342839b7e6d3/lib/src/main/java/tech/relaycorp/relaydroid/messaging/ReceiveMessages.kt#L82-L86

I came across this whilst implementing #48, because my tests were passing before I changed the unit under test.

### PR DESCRIPTION
**Pull request by sdsantos**
Fixes #49

@gnarea Notice the failing test. Feels weird that deleting the ThirdPartyEndpoint is not enough, since it triggers another error. Are we forgetting to delete something inside the `delete()` method?

### CODE REVIEW

File: lib/src/test/java/tech/relaycorp/awaladroid/messaging/ReceiveMessagesTest.kt [hunk 1]
```diff
@@ -134,6 +135,47 @@ internal class ReceiveMessagesTest : MockContextTestCase() {
...
+        val channel = createEndpointChannel(RecipientAddressType.PUBLIC)
+        val parcel = buildParcel(channel)
+        var ackWasCalled = false
+        val parcelCollection = parcel.toParcelCollection { ackWasCalled = true }
+        val collectParcelsCall = CollectParcelsCall(Result.success(flowOf(parcelCollection)))
+        pdcClient = MockPDCClient(collectParcelsCall)
+
+        channel.firstPartyEndpoint.delete()
+
+        val messages = subject.receive().toCollection(mutableListOf())
```
Comment (gnarea) [inline lib/src/test/java/tech/relaycorp/awaladroid/messaging/ReceiveMessagesTest.kt:152]: As you noticed, this is failing with the error: `MissingKeyException: There is no session key for 03d6f89f597e881f275831faaa7abb92553f18fc563e53494372db18461533178`.

That's because this test currently simulates a situation where the 1st party endpoint exists when we start collecting parcels, but no longer exists by the time we get the parcel. However, I think what you meant to simulate is the scenario where the 1st party endpoint didn't even exist when parcel collection started -- that is, `parcel.recipientAddress != channel.firstPartyEndpoint.privateAddress` is what you want to replicate.

I think the former is worth testing to make sure it's handled (I don't think I considered this scenario but it's great we came across it as it could certainly happen in real life!)

I'm not sure we can test the latter, but I could be wrong: If the 1st party endpoint didn't exist when parcel collection started (because it never existed or it was deleted), then that should/will throw an `InvalidMessageException` in:

https://github.com/relaycorp/awala-endpoint-android/blob/bad95859feadbf8f09082c9e3aa3d56854c6d566/lib/src/main/java/tech/relaycorp/awaladroid/messaging/ReceiveMessages.kt#L84-L92

... because the sender's PDA wouldn't have been issued by any id certificate of our 1st party endpoints.

Thoughts?

**Review by gnarea — CHANGES_REQUESTED** [review]

File: lib/src/test/java/tech/relaycorp/awaladroid/messaging/ReceiveMessagesTest.kt (hunk 1 above)
Comment (gnarea) [reply lib/src/test/java/tech/relaycorp/awaladroid/messaging/ReceiveMessagesTest.kt:152]: By "I think the former is worth testing to make sure it's handled" I mean add a `catch` for `MissingKeyException`

**Review by gnarea — APPROVED** [review]
